### ISSUE TITLE
HelloPlugin3 example does not compile

### ISSUE THREAD

**Issue by fthomas** [sbt/website#221]
The `HelloPlugin3` in [02-Plugins.md](https://github.com/sbt/website/blob/master/src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/02-Plugins.md) contains this code:
```scala
  lazy val helloCommand =
    Command.command("hello") { (state: State) =>
      println(greeting.value)
      state
    }
```
It calls `.value` on the `SettingKey` `greeting` outside of a task or setting macro. I've done something similar in my own plugin which gave me the following compile error:
```
`value` can only be used within a task or setting macro, such as :=, +=, ++=, Def.task, or Def.setting
```
So I guess this example also does not compile.

What would be an idiomatic way to implement `helloCommand`? Maybe like this:
```scala
  lazy val helloCommand =
    Command.command("hello") { (state: State) =>
      println(Project.extract(state).get(greeting))
      state
    }
```
?

**Comment by guersam** [comment]
+1, also, [Plugin Best Practices](http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#Use+settings+and+tasks.+Avoid+commands%2E) section recommends tasks rather than commands so that I'd suggest that we replace every `helloCommand` in that section with `helloTask`, which will make `greeting.value` work again.

**Comment by guersam** [comment]
Opened #232 fixing `HelloWorld3` only.
