### ISSUE TITLE
"Getting the right Scala version with %%" outdated. 

### ISSUE THREAD

**Issue by xuwei-k** [sbt/website#456]
I think these descriptions are right in sbt 0.11. but sbt introduce the "binaryVersion" since version 0.12.

> The complexity in practice is that often a dependency will work with a slightly different Scala version; but %% is not smart about that. So if the dependency is available for 2.10.1 but you’re using scalaVersion := "2.10.4", you won’t be able to use %% even though the 2.10.1 dependency likely works. If %% stops working, just go see which versions the dependency is really built for, and hardcode the one you think will work (assuming there is one).

- http://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#Getting+the+right+Scala+version+with
- https://github.com/sbt/website/blob/6a588cdf7738652fb896e4de7523dd28c1dfb232/src/reference/00-Getting-Started/08-Library-Dependencies.md#getting-the-right-scala-version-with-

> 実際のところの複雑な問題として、依存ライブラリはしばしば少しくらい違った Scala バージョンでも動作するのだが、 %% はこれについてそこまで賢くはない。 もしある依存ライブラリが Scala 2.10.1 に対してビルドされているとして、 君のプロジェクトが scalaVersion := "2.10.4" と指定している場合、 その 2.10.1 に依存するライブラリがおそらく動作するにも関わらず %% を使うことはできない。 もし %% が動かなくなったら、依存ライブラリが使っている実際のバージョンを確認して、 動くだろうバージョン（それがあればの話だけど）に決め打ちすればいい。

- http://www.scala-sbt.org/1.x/docs/ja/Library-Dependencies.html#%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E6%AD%A3%E3%81%97%E3%81%84+Scala+%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92%E5%85%A5%E6%89%8B%E3%81%99%E3%82%8B
- https://github.com/sbt/website/blob/6a588cdf7738652fb896e4de7523dd28c1dfb232/src/reference/ja/00-Getting-Started/08-Library-Dependencies.md#-を使って正しい-scala-バージョンを入手する

**Comment by eed3si9n** [comment]
ok. Let's remove the section from getting started guide.

**Comment by eed3si9n** [comment]
> So if the dependency is available for 2.10.1 but you’re using scalaVersion := "2.10.4", you won’t be able to use %% even though the 2.10.1 dependency likely works. 

The document likely means that if the library foo publishes `foo_2.12.4`, you can't use `%%`. This does occasionally happen still. Most notably Scala Paradise is published with "full" Scala version suffix since compiler goes not guarantee binary compatibility between versions. But this is exceedingly rare. The way it's written is misleading because it sounds like there's something special about libraries published for 2.10.1 or 2.10.4.

As I suggested in August, I think it's best to remove the passage.
